apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: frontend
spec:
  service:
    name: frontend
  calls:
    - name: recommendationservice
      type: http
      resources:
        - path: /recommendations
          methods:
            - GET
    - name: productcatalogservice
      type: http
      resources:
        - path: /products
          methods:
            - GET